### PR TITLE
Pull in upstream changes from cisagov/skeleton-ansible-role

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request pulls in the upstream changes from [cisagov/skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role).  It also adapts the code to support both the PCA-specific version of the Server Set up script and the latest version from GitHub.

## 💭 Motivation and Context

This way the repo is current, @hillaryj is now a Code Owner, and we can support both the PCA folks and the assessment folks in the COOL.

## 🧪 Testing

All pre-commit hooks and molecule tests pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
The JavaScript failure is a red herring and can be ignored.  I don't know why LGTM insists there is JS code in this repo.

**Review by dav3r — APPROVED** [review]
Looking good!  🎣 

Something to consider- should we rename `files/ServerSetup.sh` to something like `files/PCAServerSetup.sh` to make its purpose a bit clearer?

**Comment by jsf9k** [comment]
> Something to consider- should we rename `files/ServerSetup.sh` to something like `files/PCAServerSetup.sh` to make its purpose a bit clearer?

You are wise as always.  See commit 84cdf55.

**Review by felddy — APPROVED** [review]
Looks good.  Check the JavaScript yo!  You got your gulp and grunt all tangled up in the yarns.  🧶

**Pull request merged**
